//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public int SOHD { get; set; }
        public int MASACH { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
