//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public HOADON()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int SOHD { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<double> GIAMGIA { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<int> MAND { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
        public string DIACHIGIAO { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
    }
}
