//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public NGUOIDUNG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public int MAND { get; set; }
        public string TENND { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string USERNAME { get; set; }
        public string PASS { get; set; }
        public Nullable<int> QUYEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string GIOITINH { get; set; }
        public string EMAIL { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}
