//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SACHEntities1 : DbContext
    {
        public QL_SACHEntities1()
            : base("name=QL_SACHEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANNER> BANNERs { get; set; }
        public DbSet<CHITIETHD> CHITIETHDs { get; set; }
        public DbSet<CHITIETPN> CHITIETPNs { get; set; }
        public DbSet<CHUCVU> CHUCVUs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBANs { get; set; }
        public DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public DbSet<SACH> SACHes { get; set; }
        public DbSet<TACGIA> TACGIAs { get; set; }
        public DbSet<THELOAI> THELOAIs { get; set; }
    }
}
