//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public SACH()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
            this.CHITIETPNs = new HashSet<CHITIETPN>();
        }
    
        public int MASACH { get; set; }
        public Nullable<int> MATHELOAI { get; set; }
        public string TENSACH { get; set; }
        public string HINH { get; set; }
        public Nullable<int> MATACGIA { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> GIAMGIA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string MOTA { get; set; }
        public string TINHTRANG { get; set; }
        public Nullable<int> MANXB { get; set; }
        public Nullable<int> MOI { get; set; }
    
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual ICollection<CHITIETPN> CHITIETPNs { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
        public virtual TACGIA TACGIA { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
